apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aldeploy
  name: aldeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aldeploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: aldeploy
    spec:
      containers:
      - image: httpd:alpine3.20
        name: httpd