apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: FEDeploy
  name: FEDeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: FEDeploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: FEDeploy
    spec:
      containers:
      - image: httpd:alpine3.20
        name: httpd