apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mealie
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v1.12.0
          name: mealie
          ports: 
            - containerPort: 9000
          volumeMounts:
            - mountPath: /app/data
              name: mealie-storage
      volumes:
        - name: mealie-storage
          persistentVolumeClaim:
            claimName: mealie-storage

